travis:
  secure:
    BINSTAR_TOKEN: cucnKUBp5YW1/HT5z2vIb74j8ljmxUN/bwhdzr5IfB+tCULFyt/PhcsagI4JYNSajgvpvQy9hmA7jMBQDJS8qlYK1DtgFazeUeTA2pHuwNOTvWflC7jpJ9SN4n2CXZzW7OqRqz7Qwh/CXxvq7rWR5TjcFoMP8fOfhoJQVsVUya7YAYz9Ni6oOBbbZNy4AaOfgYy5BckbnMiAewkDqCPt2jV0DmNwIym+pRjfk91lw8RkEKpPMzCPfUtp5zM+Jw2DrV31KpHVxBEicyQMhxcFAc/YntQELpBbV/KzAbU0O9qRQsLYwM+tIpdwtZ9DRroTAgihiqyZsYY0nR+D2yCNmdq1/LpB4q5bajVzxdLfWLWX7yrrrQXgYKt3QPjMU82xbEItIdh2zRu+X8bJYEZTJeZclW5XhcIGs2uY31en1VXC6FxVba5/tKFDfTsRmhqTU0C6Bhmfx16t7TeH3D1UOQnaGN3o+ww4Zf6mF2KJIZGVzaa6auh8M/wPQGiJofnSqakyuupPz25o8OOankw1pEHuo65WE2AmKIHTkVJ9ds8IR6x4Ey1KYILhGvcplxQRWnQojeLj6ypYR/CX+66fR1BvHtiQXxtKawczesI35lYfV+wB1gakHkdz+UnHH1Ex4ku2v+FN/lTCapmwFG9UR28m1Nz9AyySuQvPa7f/cqY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
